from fastapi import FastAPI, Query, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel
from typing import List, Optional
import asyncio
import os
import time # For generating unique filenames
import re # For sanitizing filenames
from main import GroqKeywordExpander, QueryBuilder, LiteratureCollector, REPORTS_DIR

app = FastAPI()

# Ensure the reports directory exists (though main.py also does this)
os.makedirs(REPORTS_DIR, exist_ok=True)

class ExpandRequest(BaseModel):
    keywords: str

class SearchRequest(BaseModel):
    keywords: List[str]
    max_results: int = 20 # Default to a smaller number for web UI
    year_low: Optional[int] = None
    year_high: Optional[int] = None
    # output_file is no longer needed here, will be generated by backend

@app.post("/expand_keywords")
async def expand_keywords_api(req: ExpandRequest): # Renamed to avoid conflict with function name
    expander = GroqKeywordExpander()
    expanded_terms = await expander.expand_keywords(req.keywords)
    return {"expanded_terms": expanded_terms}

@app.post("/search_papers")
async def search_papers_api(req: SearchRequest): # Renamed to avoid conflict
    if not req.keywords:
        raise HTTPException(status_code=400, detail="Keywords cannot be empty")
    
    query_engine = QueryBuilder(req.keywords)
    search_query = query_engine.build_query()
    
    # Generate a unique and safe filename for the XLSX report
    safe_keywords_part = re.sub(r'[^\w-]', '', "_".join(req.keywords[:2]))[:50] # Use first 2 keywords, sanitize
    timestamp = int(time.time())
    xlsx_filename = f"report_{safe_keywords_part}_{timestamp}.xlsx"
    
    collector = LiteratureCollector()
    try:
        await collector.collect(
            search_query, 
            req.max_results, 
            output_filename=xlsx_filename, # Pass only the filename
            year_low=req.year_low, 
            year_high=req.year_high
        )
        return {
            "message": f"文献已处理并保存到 {xlsx_filename}",
            "papers": collector.results
        }
    except Exception as e:
        # Log the exception e for debugging on the server
        print(f"Error during paper collection: {e}")
        raise HTTPException(status_code=500, detail=f"处理文献时发生错误: {str(e)}")

@app.get("/download_xlsx/{filename:path}")
async def download_xlsx(filename: str):
    file_path = os.path.join(REPORTS_DIR, filename)
    if not os.path.isfile(file_path):
        raise HTTPException(status_code=404, detail="文件未找到或尚未生成")
    
    # Sanitize filename for download to prevent security issues, though it was generated safely
    safe_download_name = os.path.basename(filename) 

    return FileResponse(
        path=file_path, 
        media_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        filename=safe_download_name
    ) 